name: Test
on: [ push ]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build docker images
        run: make build
      - name: Run tests
        run: make check
